### ISSUE TITLE
how can I construct signature list to invoking contract parameter?

### ISSUE THREAD

**Issue by qiluge** [Cryptonomic/ConseilJS#257]
this code seems normally:
```
let conseiljs = require('conseiljs');

const sendTx = async () => {
    const tezosServer = "https://rpcalpha.tzbeta.net:443";
    const keys = conseiljs.KeyStore = {
        "publicKey": "edpkurPCz2x6ivkYiFNR9aRBXdjq7S2o4PRopiZsYYtfjBvfb7LuAw",
        "privateKey": "edskS4DLuVELALQBoZ18uQkRRNxyaGatYCN66gmuHFRSDLanMEqiLcy7G43E5Dh7sxZqZz4Yi3YcaZZkgfDRmCmX4vCCKgWRmn",
        "publicKeyHash": "tz1WfxXzNgcsMrQBV6YHChmyQgNVvfo44ihi",
        "seed": "",
        "storeType": 1
    };
    const contractAddress = "KT1TPBnfPq7XpCjL11HTzAeBkyxrSxUuskS9";
    const contractParameters = `parameter (or (unit %default) (pair %withdraw (pair (pair (mutez %amount) (list %signatures signature)) (address %to)) (string %txId)));`;
    const entryPoints = await conseiljs.TezosContractIntrospector.generateEntryPointsFromParams(contractParameters);
    entryPoints.forEach(p => {
        console.log(`${p.name}(${p.parameters.map(pp => (pp.name || 'unnamed') + '/' + pp.type).join(', ')})`);
    });
    const parameter = entryPoints[1].generateInvocationString(1200000,
        "edsigtt9FQZSbtLvLx8UVZA1RJ29R7V9WUmmoSBjCcww1Y1pg3aXqWjspCFRc9kJ1MocXV7sMeULWtJuD8XLszQCk4J5FWC5ykh,edsigtpzq77tPRMeK1n9kdUiTroMfvnmGBXiQNib5cpRnAi4tiUReVydHQskB3q4hLvkaxpDYqP7ecUXzc2dR1sAvvYDbMG1idL",
        "tz1WfxXzNgcsMrQBV6YHChmyQgNVvfo44ihi", "123123123");
    console.log("parameter is %s", parameter);
    const nodeResult = await conseiljs.TezosNodeWriter.sendContractInvocationOperation(tezosServer, keys, contractAddress,
        0, 1000000, '', 60000, 800000, 'Withdraw',
        parameter, conseiljs.TezosParameterFormat.Michelson);
    console.log(nodeResult["operationGroupID"]);
};

sendTx().catch(err => console.log(err));
```
But It failed:
```
Default(unnamed/unit)
Withdraw(Amount/mutez, unnamed/list (signature), To/address, TxId/string)
parameter is (Right (Pair (Pair (Pair 1200000 (edsigtt9FQZSbtLvLx8UVZA1RJ29R7V9WUmmoSBjCcww1Y1pg3aXqWjspCFRc9kJ1MocXV7sMeULWtJuD8XLszQCk4J5FWC5ykh,edsigtpzq77tPRMeK1n9kdUiTroMfvnmGBXiQNib5cpRnAi4tiUReVydHQskB3q4hLvkaxpDYqP7ecUXzc2dR1sAvvYDbMG1idL)) tz1WfxXzNgcsMrQBV6YHChmyQgNVvfo44ihi) 123123123))
Error: invalid syntax at line 1 col 35:

  (Right (Pair (Pair (Pair 1200000 (edsigtt9FQZSbtLvLx8UVZA1RJ29R7V9WUmmoSBjCcww1Y1pg3aXqWjspCFRc9kJ1MocXV7sMeULWtJuD8XLszQCk4J5FWC5ykh,edsigtpzq77tPRMeK1n9kdUiTroMfvnmGBXiQNib5cpRnAi4tiUReVydHQskB3q4hLvkaxpDYqP7ecUXzc2dR1sAvvYDbMG1idL)) tz1WfxXzNgcsMrQBV6YHChmyQgNVvfo44ihi) 123123123))
                                    ^
    at Lexer._token (G:\工作\tezos\xtz-ledger-test\node_modules\moo\moo.js:518:13)
    at Lexer.next (G:\工作\tezos\xtz-ledger-test\node_modules\moo\moo.js:465:19)
    at Parser.feed (G:\工作\tezos\xtz-ledger-test\node_modules\nearley\lib\nearley.js:270:30)
    at preProcessMichelsonScript.forEach.p (G:\工作\tezos\xtz-ledger-test\node_modules\conseiljs\dist\chain\tezos\TezosLanguageUtil.js:157:63)
    at Array.forEach (<anonymous>)
    at Object.translateParameterMichelsonToMicheline (G:\工作\tezos\xtz-ledger-test\node_modules\conseiljs\dist\chain\tezos\TezosLanguageUtil.js:157:41)
    at constructContractInvocationOperation (G:\工作\tezos\xtz-ledger-test\node_modules\conseiljs\dist\chain\tezos\TezosNodeWriter.js:310:79)
    at Object.<anonymous> (G:\工作\tezos\xtz-ledger-test\node_modules\conseiljs\dist\chain\tezos\TezosNodeWriter.js:291:33)
    at Generator.next (<anonymous>)
    at fulfilled (G:\工作\tezos\xtz-ledger-test\node_modules\conseiljs\dist\chain\tezos\TezosNodeWriter.js:4:58)
```
I think that I am passing wrong format parameter of signature list. So, what format of signature list should I construct?

**Comment by qiluge** [comment]
I have tried these case, but all failed.
```
["edsigtt9FQZSbtLvLx8UVZA1RJ29R7V9WUmmoSBjCcww1Y1pg3aXqWjspCFRc9kJ1MocXV7sMeULWtJuD8XLszQCk4J5FWC5ykh,edsigtpzq77tPRMeK1n9kdUiTroMfvnmGBXiQNib5cpRnAi4tiUReVydHQskB3q4hLvkaxpDYqP7ecUXzc2dR1sAvvYDbMG1idL"]
```
```
["edsigtt9FQZSbtLvLx8UVZA1RJ29R7V9WUmmoSBjCcww1Y1pg3aXqWjspCFRc9kJ1MocXV7sMeULWtJuD8XLszQCk4J5FWC5ykh","edsigtpzq77tPRMeK1n9kdUiTroMfvnmGBXiQNib5cpRnAi4tiUReVydHQskB3q4hLvkaxpDYqP7ecUXzc2dR1sAvvYDbMG1idL"]
```

**Comment by anonymoussprocket** [comment]
Please ask in the [developer room on riot](https://matrix.to/#/!rUwpbdwWhWgKINPyOD:cryptonomic.tech?via=cryptonomic.tech&via=matrix.org&via=tzchat.org)
