### ISSUE TITLE
`KeyStoreUtils.generateIdentity` throws `TypeError: unsupported input type for seed`

### ISSUE THREAD

**Issue by abrkn** [Cryptonomic/ConseilJS#302]
Code:

```typescript
  const mnemonic = await KeyStoreUtils.generateIdentity();
  console.log({ mnemonic });
```

Error:

```
      at f (node_modules/libsodium-wrappers-sumo/dist/modules-sumo/libsodium-wrappers.js:1:13307)
      at k (node_modules/libsodium-wrappers-sumo/dist/modules-sumo/libsodium-wrappers.js:1:13478)
      at Object.xt [as crypto_sign_seed_keypair] (node_modules/libsodium-wrappers-sumo/dist/modules-sumo/libsodium-wrappers.js:1:58592)
      at Object.keys (node_modules/conseiljs-softsigner/dist/utils/WrapperWrapper.js:23:23)
```

**Comment by anonymoussprocket** [comment]
Hi @abrkn, please use the latest iteration of this code which has now moved to [conseiljs-softsigner](https://www.npmjs.com/package/conseiljs-softsigner). The code is in a [separate repo](https://github.com/Cryptonomic/ConseilJS-softsigner). The unit test examples for this function [are available](https://github.com/Cryptonomic/ConseilJS-softsigner/blob/master/test/KeyStoreUtils.spec.ts#L10) as well.
