### ISSUE TITLE
TypeError: FetchSelector.actualFetch is not a function

### ISSUE THREAD

**Issue by Tanmoy741127** [Cryptonomic/ConseilJS#387]
I was going through the docs. All goes well but something break in activate_account

The code is :

```
const tezosNode = 'https://tezos-florence.cryptonomic-infra.tech:443'; 

async function activateAccount() {

    const keystore = {
        publicKey: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx',
        secretKey: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        publicKeyHash: 'XXXXXXXXXXXXXXXXXXXxx',
        seed: '',
        storeType: conseiljs.KeyStoreType.Fundraiser
    };

    const signer = await conseiljssoftsigner.SoftSigner.createSigner(conseiljs.TezosMessageUtils.writeKeyWithHint(keystore.secretKey, 'edsk'));
    const result = await conseiljs.TezosNodeWriter.sendIdentityActivationOperation(tezosNode, signer, keystore, 'XXXXXXXXXXXXXXXXXXXXXXXXXX');
    console.log(`Injected operation group id ${result.operationGroupID}`)
}

activateAccount();

```
ERROR LOGS :
```
node:15191) UnhandledPromiseRejectionWarning: TypeError: FetchSelector.actualFetch is not a function
    at FetchSelector.fetch (/home/tanmoy/Desktop/tezos_test/node_modules/conseiljs/dist/utils/FetchSelector.js:9:55)
    at performGetRequest (/home/tanmoy/Desktop/tezos_test/node_modules/conseiljs/dist/chain/tezos/TezosNodeReader.js:25:16)
    at getBlock (/home/tanmoy/Desktop/tezos_test/node_modules/conseiljs/dist/chain/tezos/TezosNodeReader.js:47:16)
    at Object.<anonymous> (/home/tanmoy/Desktop/tezos_test/node_modules/conseiljs/dist/chain/tezos/TezosNodeReader.js:59:32)
    at Generator.next (<anonymous>)
    at /home/tanmoy/Desktop/tezos_test/node_modules/conseiljs/dist/chain/tezos/TezosNodeReader.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/tanmoy/Desktop/tezos_test/node_modules/conseiljs/dist/chain/tezos/TezosNodeReader.js:4:12)
    at Object.getBlockAtOffset (/home/tanmoy/Desktop/tezos_test/node_modules/conseiljs/dist/chain/tezos/TezosNodeReader.js:55:16)
    at /home/tanmoy/Desktop/tezos_test/node_modules/conseiljs/dist/chain/tezos/TezosNodeWriter.js:146:71
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15191) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:15191) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Wozacosta** [comment]
https://github.com/Cryptonomic/ConseilJS/issues/387 

>  Further more, it is necessary to provide a logger and fetch references as specified below. This is done separately to allow use of proxy-aware fetch for example.

**Comment by AkshitV** [comment]
HI, 
Facing similar issue, any update on this? Or any alternates?
